version: "3.5"
services:
  website:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   ports:
    #     - "127.0.0.1:5000:5000"
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    image: ${CONTAINER_NAME}:dev
    container_name: ${CONTAINER_NAME}
    environment:
      APP_PORT: ${APP_PORT}
